name = "rotaract-district-3192"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "rotaract-district-3192"

[vars]
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_Z3VpZGluZy1nb3NoYXdrLTkuY2xlcmsuYWNjb3VudHMuZGV2JA"
NEXT_PUBLIC_CLERK_SIGN_IN_URL = "/sign-in"
NEXT_PUBLIC_CLERK_SIGN_UP_URL = "/sign-up"
# CLERK_SECRET_KEY is set as an encrypted secret via: wrangler secret put CLERK_SECRET_KEY
